/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.Ejemplos;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;  // hereda de statement. Añade seguridad
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;


public class Conectores {
	private final static int OK = 1;
	private final static int NO_OK = 0;

	private static Scanner sc;
	
	// URL DE CONEXION A LA BASE DE DATOS
	private final static String URL_CONEXION = "jdbc:mysql://localhost:3306/empleados_departamentos";
	private final static String DB_USER = "root";
	private final static String DB_PASSWORD = "123456789";
	
	// CONSTANTES -- Para pasar campos a una query, usamos interrogantes por motivos de seguridad
	// si no se hace así, se puede hacer un ataque por inyección de código 
	// al guardar un código a ejecutar con el ? este, al ser consultado NO SE EJECUTA. Ejemplo Alert de Javascript
	private final static String CREAR_EMPLEADO = "INSERT INTO empleados "
			   								   + "(nDIEmp, nomEmp, sexEmp, fecNac, fecIncorporacion, salEmp, comisionE, "
			   								   + " cargoE, jefeID, codDepto) "
			   								   + "VALUES (?, ?, ?, ?, sysdate(), ?, ?, ?, ?, ?)";
	
	private final static String CONSULTAR_EMPLEADO = "SELECT nDIEmp, nomEmp, sexEmp, fecNac, fecIncorporacion, salEmp, "
												   + "comisionE, cargoE, jefeID, codDepto "
												   + "FROM empleados "
												   + "WHERE nDIEmp = ?";
	
	private final static String ACTUALIZAR_SALARIO = "UPDATE empleados "
												   + "SET salEmp = ? "
												   + "WHERE nDIEmp = ?";
	
	private final static String BORRAR_EMPLEADO = "DELETE FROM empleados " 
												+ "WHERE nDIEmp = ?";
	
	

	
	// CREAR CONEXION
	private static Connection getDbConection() {
		Connection connection = null;
		
    	// Registramos el driver de MySQL
    	try { 
    		  Class.forName("com.mysql.cj.jdbc.Driver");
    	} catch (ClassNotFoundException ex) {
    	    System.out.println("Error al registrar el driver de PostgreSQL: " + ex);
    	}  
    	
    	// Conectamos con la base de datos 
    	try {
    		connection = DriverManager.getConnection(URL_CONEXION, DB_USER, DB_PASSWORD);
			connection.setAutoCommit(false);
			
			//Comprobamos is la conexion es valida 
			boolean valid = connection.isValid(50000);
			System.out.println(valid ? "CONNECTION OK" : "CONNECTION NO OK");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

    	return connection;
	}
	
	// AÑADIR EMPLEADO
	private static int crearEmpleado(String idPersonal, String nbPersonal, String sexoPersonal,
									 String fechNaci, int sueldo, int comision, String puesto, String IDJefe,
									 String numDept) {
		int result = NO_OK; 
		
		PreparedStatement preparedStatement = null;
		Connection connection = getDbConection();
		
		if (null != connection) {
			try {
				// Decimos que sentencia queremos ejecutar
				preparedStatement = connection.prepareStatement(CREAR_EMPLEADO);
				// Asignamos valor a los campos (interrogantes) de la sentencia
				preparedStatement.setString(1, idPersonal);
				preparedStatement.setString(2, nbPersonal);
				preparedStatement.setString(3, sexoPersonal);
				preparedStatement.setString(4, fechNaci);
				preparedStatement.setInt(5, sueldo);
				preparedStatement.setInt(6, comision);
				preparedStatement.setString(7, puesto);
				preparedStatement.setString(8, IDJefe);
				preparedStatement.setString(9, numDept);
				
				// Se EJECUTA la QUERY
				int filasInsertadas = preparedStatement.executeUpdate();
				
				// Si se ha insertado una fila, hago commit, y si no, rollback
				if (filasInsertadas == 1) {
					connection.commit();
					result = OK;
				} else {
					connection.rollback();
				}

				// IMPORTANTE - CERRAR Statement y Connection
				preparedStatement.close();
				connection.close();
			} catch (SQLException e) {
				e.printStackTrace();
			} 
		}
		
		return result;
	}

	private static int PedirNumero(String s) 
	{
		System.out.print(s);
		int numeroInfo = 0;
		boolean esNumero;
		do {
			try {
				do {
					numeroInfo = sc.nextInt();
				}
				while (numeroInfo <= 0);
				esNumero = true;
			} catch (Exception ex)
			{
				System.out.println("El numero introducido no es un numero");
				esNumero = false;
			}
		} while (!esNumero);
		
		
		return numeroInfo;
	}

	private static String PedirTexto(String s)
	{
		System.out.print(s);
		String info;
		do
		{
			info = sc.nextLine();
		}
		while(info.isBlank());

		return info;
	}

	// CONSULTAS
	private static void consultarEmpleado(String idEmpleado) {
		try (Connection connection = getDbConection();
			 PreparedStatement preparedStatement = connection.prepareStatement(CONSULTAR_EMPLEADO)) {
			
			// que en el parámetro uno ponga idEmpleado
			preparedStatement.setString(1, idEmpleado);
			// no lo puedo poner en el try para que se cierre auto, porque le pasamos un parámetro a la query
			// ResultSet es un HASHMAP
	        ResultSet rs = preparedStatement.executeQuery();
			
	        // se imprime para todos los elementos devueltos en la consulta
	        while (rs.next()) {
	        	System.out.println("======= INICIO DATOS USUARIO ======");
	      
	            System.out.println("ID: " + idEmpleado);
	            System.out.println("Nombre: " + rs.getString("nomEmp"));
	            System.out.println("Sexo: " + rs.getString("sexEmp"));
	            System.out.println("Fecha nacimiento: " + rs.getString("fecNac"));
	            System.out.println("Fecha incorporación: " + rs.getDate("fecIncorporacion"));
	            System.out.println("Salario: " + rs.getInt("salEmp"));
	            System.out.println("Comisión: " + rs.getString("comisionE"));
	      
	            System.out.println("======= FIN DATOS USUARIO ======");
	        }
	        
	        rs.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}
	
	// MODIFICA UN EMPLEADO
	private static int actualizarEmpleado(String idEmpleado, int salario) {
		int result = NO_OK; 
		
		try (Connection connection = getDbConection();
			 PreparedStatement preparedStatement = connection.prepareStatement(ACTUALIZAR_SALARIO)) {
			
			preparedStatement.setDouble(1, salario);
			preparedStatement.setString(2, idEmpleado);
			
			// en este caso no tenemos ResultSet. ExecuteUpdate nos devuelve el número de filas afectadas
			int filasActualizadas = preparedStatement.executeUpdate();
			
			if (filasActualizadas == 1) {
				connection.commit();
				result = OK;
			} else {
				connection.rollback();
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return result;
	}

	// BORRAR EMPLEADO
	private static int borrarEmpleado(String idEmpleado) {
		int result = NO_OK; 
		
		try (Connection connection = getDbConection();
			 PreparedStatement preparedStatement = connection.prepareStatement(BORRAR_EMPLEADO)) {
			preparedStatement.setString(1, idEmpleado);
			
			int filasBorradas = preparedStatement.executeUpdate();
			
			if (filasBorradas == 1) {
				connection.commit();
				result = OK;
			} else {
				connection.rollback();
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return result;	
	}


	// MAIN
    public static void main(String args[]) {
		sc = new Scanner(System.in);

    	crearEmpleado(PedirTexto("Introduzca el ID del personal: "),PedirTexto("Introduzca el nombre del personal: "),
				PedirTexto("Introduzca el sexo del personal (M/F): "),PedirTexto("Introduzca el año de nacimiento del personal: "),
				PedirNumero("Introduzca el saldo del personal: "), PedirNumero("Introduzca la comision del personal: "),
				PedirTexto("Introduzca el puesto al que aplica:"),PedirTexto("Introduzca el ID del jefe: "),
				PedirTexto("Introduzca el numero de departamento: "));

    	consultarEmpleado("1");
    	
    	if (OK == actualizarEmpleado("1", 70000)) {
    		System.out.println("Empleado actualizado");
    	} else {
    		System.out.println("Empleado no actualizado");	
    	}
    	
    	consultarEmpleado("1");
    	
    	int resultado = borrarEmpleado("1");
    	
    	if (OK == resultado) {
    		System.out.println("Empleado borrado");
    	} else {
    		System.out.println("Empleado no no borrado");	
    	}
    	
    	consultarEmpleado("1");
    }

}
